### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by khiner** [brianmhess/cassandra-loader#8]
```
./cassandra-loader -f uuids.csv.0 -host <host> -schema "<cf>.<schema>(...)"
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
*** Processing uuids.csv.0
Lines Processed: 	100000  Rate: 	4347 (4347)
*** DONE: uuids.csv.0  number of lines processed: 101924 (101924 inserted)
Lines Processed: 	101924  Rate: 	4246
Exception in thread "main" java.lang.NullPointerException
	at com.datastax.loader.CqlDelimLoad.cleanup(CqlDelimLoad.java:347)
	at com.datastax.loader.CqlDelimLoad.run(CqlDelimLoad.java:443)
	at com.datastax.loader.CqlDelimLoad.main(CqlDelimLoad.java:451)
```

**Comment by brianmhess** [comment]
I believe this issue was addressed (in 0.0.12 or 0.0.13). Are you still seeing this issue with 0.0.14 (the latest)?

**Comment by masumsoft** [comment]
I'm facing the same issue with 0.0.15 and cassandra 2.1.8

**Comment by brianmhess** [comment]
@masumsoft - can you share the NPE you are getting with 0.0.15?

**Comment by masumsoft** [comment]
@brianmhess here is the NPE

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
*** Processing my.csv
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.datastax.loader.CqlDelimLoad.run(CqlDelimLoad.java:558)
	at com.datastax.loader.CqlDelimLoad.main(CqlDelimLoad.java:599)
Caused by: java.lang.NullPointerException
	at com.datastax.loader.parser.MapParser.parse(MapParser.java:55)
	at com.datastax.loader.parser.AbstractParser.parse(AbstractParser.java:43)
	at com.datastax.loader.parser.DelimParser.parseComplex(DelimParser.java:106)
	at com.datastax.loader.parser.DelimParser.parse(DelimParser.java:98)
	at com.datastax.loader.CqlDelimParser.parse(CqlDelimParser.java:233)
	at com.datastax.loader.CqlDelimLoadTask.execute(CqlDelimLoadTask.java:230)
	at com.datastax.loader.CqlDelimLoadTask.call(CqlDelimLoadTask.java:145)
	at com.datastax.loader.CqlDelimLoadTask.call(CqlDelimLoadTask.java:69)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by KenMcK1** [comment]
I ran into this as well using the code on master. It happens when a map field has no value. We had this column in our Cassandra schema:

```
tech map<text, text>
```

If I remove this column from the command-line schema of both unloader and loader, the loader works.

**Comment by brianmhess** [comment]
@KenMcK1 , do you mean that if you had a schema like (a int, b map<text,text>, c int) and the line was:
1,,3

Then you'd have the error?  If not, can you provide a sample row and schema?

**Comment by KenMcK1** [comment]
Yes. I'm actually using tab delimiters, but that shouldn't make a difference. The table is like this:

    CREATE TABLE mytable (
      id text,
      a text,
      b map<text, text>,
      c text,
      d text,
      PRIMARY KEY (id)
    );

Most of the rows have a value for column b, but not all.

    1,A1,{B1:VAL1},C1,D1
    2,A2,,C2,D2

The second row causes the exception. But there is also another problem I just ran into. If I make the data this:

    1,A1,{B1:VAL1},C1,D1
    2,A2,{B2:VAL2},C2,D2

The load works but I end up with rows like this in the table:

    1,A1,{B1:VAL1},C1,D1
    2,A2,{B1:VAL1, B2:VAL2},C2,D2

The map value appears to be inserted in every row after it's read. This accumulates until the last row loaded has every map value read during the run:

     id | a  | b                                                                      | c  | d
    ----+----+------------------------------------------------------------------------+----+----
      4 | A4 |               {'B1': 'VAL1', 'B2': 'VAL2', 'B3': 'VAL3', 'B4': 'VAL4'} | C4 | D4
      3 | A3 |                             {'B1': 'VAL1', 'B2': 'VAL2', 'B3': 'VAL3'} | C3 | D3
      5 | A5 | {'B1': 'VAL1', 'B2': 'VAL2', 'B3': 'VAL3', 'B4': 'VAL4', 'B5': 'VAL5'} | C5 | D5
      2 | A2 |                                           {'B1': 'VAL1', 'B2': 'VAL2'} | C2 | D2
      1 | A1 |                                                         {'B1': 'VAL1'} | C1 | D1

**Comment by brianmhess** [comment]
That was actually Issue 14. I fixed that in v0.0.16. Have you tried with that?

**Comment by KenMcK1** [comment]
0.0.16 fixes the duplicate map values but not the NPE. It's easy to reproduce with the example schema and first data file above. Setting nullString to NULL doesn't help.

    $ cat myfile.csv
    1,A1,{B1:VAL1},C1,D1
    2,A2,NULL,C2,D2
    $ cassandra-unloader
    No arguments specified
    Bad arguments
    version: 0.0.16
    ...
    $ cassandra-loader -f myfile.csv -host <cass host> -schema "mykeyspace.mytable(id, a, b, c, d)" -delim $',' -boolStyle 1_0 -nullString NULL
    ...
    *** Processing myfile.csv
    Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:188)
        at com.datastax.loader.CqlDelimLoad.run(CqlDelimLoad.java:558)
        at com.datastax.loader.CqlDelimLoad.main(CqlDelimLoad.java:599)
    Caused by: java.lang.NullPointerException
        at com.datastax.loader.parser.MapParser.parse(MapParser.java:55)
        at com.datastax.loader.parser.AbstractParser.parse(AbstractParser.java:43)
        at com.datastax.loader.parser.DelimParser.parseComplex(DelimParser.java:106)
        at com.datastax.loader.parser.DelimParser.parse(DelimParser.java:98)
        at com.datastax.loader.CqlDelimParser.parse(CqlDelimParser.java:233)
        at com.datastax.loader.CqlDelimLoadTask.execute(CqlDelimLoadTask.java:230)
        at com.datastax.loader.CqlDelimLoadTask.call(CqlDelimLoadTask.java:145)
        at com.datastax.loader.CqlDelimLoadTask.call(CqlDelimLoadTask.java:69)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by brianmhess** [comment]
GOT IT!  Fixed in v0.0.17

**Comment by KenMcK1** [comment]
That works. Thanks!

**Comment by maskeygit** [comment]
Brian,

I tried to load the data that has Map as a column, but i get the above error. I am using Cassandra Loader 0.0.17. The problem still seem to exists. Here is my simple schema.

Customer( firstname text, phones Map<text, text>) and I am using | as delimiter.

JOHN|"{Extension|0:,Extension|1:,Extension|2:,Number|0:4322342342,Number|1:1234123412,Number|2:2342342342,Type|0:M,Type|1:D,Type|2:E}"

JOHN|NULL
If I insert NULL for phones, it loads fine.

**Comment by maskeygit** [comment]
I found out the reason why it was throwing the exception. In the above example, all Extension|0, Extension|1 and Extension|2 don't have any values. How to get around to this issue with out manually modifying the data is my next question?
